### ISSUE TITLE
Job Link Click does not work

### ISSUE THREAD

**Issue by maxiomtech** [EngageSoftware/Engage-Employment#7]
Since we upgraded to 7.3.4 the job links in the jobs listing module just reload the listing page. It does not take you to the job details.

Nothing is logged in the event log, so we're not sure what the issue is.

Any ideas?

Thanks.

**Comment by bdukes** [comment]
I haven't run into that.  Are you using Job Groups?  Do you have multiple listing and/or details modules?

**Comment by InspectorIT** [comment]
Here is a link where we are experiencing the problem: http://www.leadingagepa.org/TakeAction/Engagement/Careers.aspx -- Click on a job...

**Comment by InspectorIT** [comment]
Duh - please disregard. The client seemed to have deleted the details module :-| I just looked in the recycle bin and there it was.

Sorry for the false alarm and thank you.
